apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
  namespace: integration-ns
spec:
  template:
    metadata:
      labels:
        app: kong-migration
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kong-migration
        image: kong:3.5
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: kong-postgres-svc
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_DATABASE
          value: kong
        - name: KONG_PG_USER
          value: kong
        - name: KONG_PG_PASSWORD
          value: kongpass
        command: ["kong", "migrations", "bootstrap"]
---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy-svc
  namespace: integration-ns
spec:
  selector:
    app: kong
  type: LoadBalancer
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
      nodePort: 30443
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin-svc
  namespace: integration-ns
spec:
  selector:
    app: kong
  type: NodePort
  ports:
    - name: admin-api
      port: 8001
      targetPort: 8001
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: integration-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:3.5
        env:
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PG_HOST
          value: kong-postgres-svc
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_DATABASE
          value: kong
        - name: KONG_PG_USER
          value: kong
        - name: KONG_PG_PASSWORD
          value: kongpass
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
        ports:
        - containerPort: 8000
          name: proxy
        - containerPort: 8443
          name: proxy-ssl
        - containerPort: 8001
          name: admin-api
        readinessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /status
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 10
