apiVersion: v1
kind: ConfigMap
metadata:
  name: image-postgres-init-scripts
  namespace: integration-ns
data:
  init.sql: |
    CREATE USER parkin WITH PASSWORD 'qwerty123';
    CREATE DATABASE db_parkin_zone OWNER parkin;
    CREATE DATABASE db_parkin_users OWNER parkin;
    CREATE DATABASE db_parkin_tickets OWNER parkin;
    CREATE DATABASE db_notifications OWNER parkin;
    GRANT ALL PRIVILEGES ON DATABASE db_parkin_zone TO parkin;
    GRANT ALL PRIVILEGES ON DATABASE db_parkin_users TO parkin;
    GRANT ALL PRIVILEGES ON DATABASE db_parkin_tickets TO parkin;
    GRANT ALL PRIVILEGES ON DATABASE db_notifications TO parkin;

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: integration-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: integration-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "qwerty123"
        - name: POSTGRES_USER
          value: "postgres" # Usuario root inicial
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-scripts
        configMap:
          name: image-postgres-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: integration-ns
spec:
  selector:
    app: postgres-db
  ports:
    - port: 5432
      targetPort: 5432
