apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tickets
  namespace: integration-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-tickets
  template:
    metadata:
      labels:
        app: ms-tickets
    spec:
      containers:
      - name: ms-tickets
        image: ms-tickets:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: "postgres-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "parkin"
        - name: DB_PASSWORD
          value: "qwerty123"
        - name: DB_NAME
          value: "db_parkin_tickets"
        - name: ZONE_SERVICE_URL
          value: "http://zone-core-svc/api"
        - name: PERSONA_SERVICE_URL
          value: "http://mc-clientes-svc/api"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-tickets-svc
  namespace: integration-ns
spec:
  selector:
    app: ms-tickets
  ports:
    - port: 80
      targetPort: 4000
