apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: integration-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: RABBITMQ_URI
          value: "amqp://admin:admin@rabbitmq:5672"
        - name: DB_HOST
          value: "postgres-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "parkin"
        - name: DB_PASSWORD
          value: "qwerty123"
        - name: DB_NAME
          value: "db_notifications"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  namespace: integration-ns
spec:
  selector:
    app: notification-service
  ports:
    - port: 80
      targetPort: 3001
